#!/bin/bash
# Install essential tools for my development environment

if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "Unsupported OS."
  exit
fi

function init() {
  echo "[-] Installing Xcode Command Line Tools [-]"
  xcode-select --install

  if ! hash brew &> /dev/null; then
    echo "[-] Installing Homebrew [-]"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

# Setup initial tools
init

# Install prerequisite packages
echo "[-] Installing some prerequisite packages [-]"
brew update
brew install curl wget git coreutils watch ncdu jq fd

# Install font
echo "[-] Installing Source Code Pro Font [-]"
brew install --cask font-jetbrains-mono-nerd-font

# Backup dotfiles
function backup() {
  local backup_dir=dotfiles-bak-$(date +%s)

  mkdir ~/$backup_dir
  mv ~/.zshrc ~/$backup_dir/.zshrc
  mv ~/.zshenv ~/$backup_dir/.zshenv
  mv ~/.tmux.conf ~/$backup_dir/.tmux.conf
}
echo "[-] Backing up dotfiles [-]"
backup

# Link dotfiles
function linking() {
  ln -s $(pwd)/.zshrc ~/.zshrc
  ln -s $(pwd)/.zshenv ~/.zshenv
  ln -s $(pwd)/.tmux.conf ~/.tmux.conf
  ln -s $(pwd)/.gitignore ~/.gitignore
  ln -s $(pwd)/.fdignore ~/.fdignore
  ln -s $(pwd)/.vimrc ~/.vimrc
  ln -s $(pwd)/.ideavimrc ~/.ideavimrc

  mkdir -p ${XDG_CONFIG_HOME:=~/.config}
  ln -s $(pwd)/nvim $XDG_CONFIG_HOME/nvim
}
echo "[-] Linking dotfiles [-]"
linking

# Install some extended packages
echo "[-] Installing extended packages [-]"
brew install tmux neovim zsh-autosuggestions parallel ripgrep fzf
brew install httpie pyenv universal-ctags

# Download git-prompt.sh script
echo "[-] Downloading git-prompt.sh script [-]"
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

# Download Vim plugin manager
echo "[-] Downloading vim-plug [-]"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install default terminal emulator
echo "[-] Installing Alacritty [-]"
brew install alacritty

# Create some essential folders
echo "[-] Creating essential folders [-]"
mkdir ~/.vimsess
mkdir ~/chores
mkdir ~/repos

# Change default shell
# echo "[-] Change default shell to Zsh [-]"
# chsh -s $(which zsh)

# Notify configuration finished
echo "[-] Setup done. Run \`source ~/.zshrc\` to refresh shell config [-]"
