#!/bin/bash
# Install essential tools for my development environment

if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "Unsupported OS."
  exit
fi

function init() {
  echo "[-] Installing Xcode Command Line Tools [-]"
  xcode-select --install

  if ! hash brew &> /dev/null; then
    echo "[-] Installing Homebrew [-]"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> $HOME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

# Setup initial tools
init

# Install prerequisite packages
echo "[-] Installing some prerequisite packages [-]"
brew update
brew install curl wget git coreutils watch ncdu jq fd

# Install font
echo "[-] Installing Source Code Pro Font [-]"
brew install --cask font-sauce-code-pro-nerd-font

# Backup dotfiles
function backup() {
  local current_date=$(date +%s)
  local backup_dir=dotfiles_bak_$current_date

  mkdir ~/$backup_dir
  mv ~/.zshrc ~/$backup_dir/.zshrc
  mv ~/.zshenv ~/$backup_dir/.zshenv
  mv ~/.tmux.conf ~/$backup_dir/.tmux.conf
}
echo "[-] Backing up dotfiles [-]"
backup

# Link dotfiles
function linking() {
  ln -s $(pwd)/.zshrc $HOME/.zshrc
  ln -s $(pwd)/.zshenv $HOME/.zshenv
  ln -s $(pwd)/.tmux.conf $HOME/.tmux.conf
  ln -s $(pwd)/.vimrc $HOME/.vimrc

  mkdir -p $HOME/.vim/after
  ln -s $(pwd)/ftplugin $HOME/.vim/after/ftplugin

  mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
  ln -s $(pwd)/alacritty $XDG_CONFIG_HOME/alacritty
}
echo "[-] Linking dotfiles [-]"
linking

# Install some extended packages
echo "[-] Installing extended packages [-]"
brew install tmux zsh-autosuggestions fzf parallel universal-ctags ripgrep pyenv
brew install lazygit httpie

# Download git-prompt.sh script
echo "[-] Downloading git-prompt.sh script [-]"
mkdir -p $HOME/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

# Download Vim plugin manager
echo "[-] Downloading vim-plug [-]"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install default terminal emulator
echo "[-] Installing Alacritty [-]"
brew install alacritty

# Create some essential folders
echo "[-] Creating essential folders [-]"
mkdir $HOME/vimsessions
mkdir $HOME/open-source
mkdir $HOME/playground

# Change default shell
# echo "[-] Change default shell to Zsh [-]"
# chsh -s $(which zsh)

# Notify configuration finished
echo "[-] Setup done. Run \`source ~/.zshrc\` to refresh shell config [-]"
