#!/bin/bash
# Setup jdtls development environment

if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "Unsupported OS."
  exit
fi

# Clone Jdtls to HOME
echo "[-] Cloning Eclipse jdtls to HOME [-]"
git clone https://github.com/eclipse-jdtls/eclipse.jdt.ls.git $HOME/eclipse.jdt.ls

# Build from source
echo "[-] Building jdtls [-]"
cd ~/eclipse.jdt.ls
JAVA_HOME=$JDK17 ./mvnw clean verify -DskipTests=true -T 5
