#!/bin/bash
# Install essential tools for my development environment

if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "Unsupported OS."
  exit
fi

function init() {
  echo "[-] Installing Xcode Command Line Tools [-]"
  xcode-select --install

  if ! hash brew &> /dev/null; then
    echo "[-] Installing Homebrew [-]"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> $HOME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

# Setup initial tools
init

# Install prerequisite packages
echo "[-] Installing some prerequisite packages [-]"
brew update
brew install curl wget git coreutils watch ncdu

# Install font
echo "[-] Installing Source Code Pro Font [-]"
brew tap homebrew/cask-fonts
brew install --cask font-sauce-code-pro-nerd-font

# Ensure Rust installation
if ! hash rustc &> /dev/null; then
  echo "[-] Installing Rust [-]"
  sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y)"
  sh -c "$(source $HOME/.cargo/env)"
fi

# Backup dotfiles
function backup() {
  local current_date=$(date +%s)
  local backup_dir=dotfiles_bak_$current_date

  mkdir ~/$backup_dir
  mv ~/.zshrc ~/$backup_dir/.zshrc
  mv ~/.tmux.conf ~/$backup_dir/.tmux.conf
}
echo "[-] Backing up dotfiles [-]"
backup

# Link dotfiles
function linking() {
  ln -s $(pwd)/.zshrc ~/.zshrc
  ln -s $(pwd)/.zshenv ~/.zshenv
  ln -s $(pwd)/.tmux.conf ~/.tmux.conf
  ln -s $(pwd)/.vimrc ~/.vimrc

  mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
  ln -s $(pwd)/alacritty $XDG_CONFIG_HOME/alacritty
}
echo "[-] Linking dotfiles [-]"
linking

# Install some extended packages
echo "[-] Installing extended packages [-]"
brew install tmux zsh-autosuggestions ripgrep lazygit pyenv

# Download git-prompt.sh script
echo "[-] Downloading git-prompt.sh script [-]"
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

# Download Vim plugin manager
echo "[-] Downloading vim-plug [-]"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install default terminal emulator
echo "[-] Installing Alacritty [-]"
brew install alacritty

# Install DB CLI client for PostgreSQL and MySQL
echo "[-] Installing DB CLI clients [-]"
brew install pgcli mycli

# Create some essential folders
echo "[-] Creating essential folders [-]"
mkdir ~/open-source
mkdir ~/playground

# Change default shell
echo "[-] Change default shell to Zsh [-]"
chsh -s $(which zsh)

# Notify configuration finished
echo "[-] Setup done. Run \`source ~/.zshrc\` to refresh shell config [-]"
