#!/bin/sh
# one-line machine health for the tmux status bar: reclaimable memory + 1m load
if [ -r /proc/meminfo ]; then
    mem=$(awk '/^MemTotal/{t=$2} /^MemAvailable/{a=$2} END{print int(a*100/t)"%"}' /proc/meminfo)
    load=$(cut -d' ' -f1 /proc/loadavg)
else
    mem=$(memory_pressure -Q | awk '/percentage/{print $5}')
    load=$(sysctl -n vm.loadavg | awk '{print $2}')
fi
echo "mem $mem free, load $load"
# vim: ft=sh
