#!/bin/bash
#vim:ft=bash

root=$MULTI_MODULES_ROOT
module_name=":$1"
test_name="com.example.$2"

echo $test_name
echo $module_name

cd $root
mvn test -Dtest=$test_name -pl $module_name -DskipTests=false

