require("which-key").add({
  { "<leader>f", ":Files<CR>", desc = "Find files" },
  { "<leader>F", ":GFiles<CR>", desc = "Find files (include ignored files)" },
  { "<leader>b", ":Buffers<CR>", desc = "Buffer list", silent = false },
  { "<leader>/", ":Rg<CR>", desc = "Grep pattern within project" },
  { "<leader>p", "\"+p", desc = "Paste marked text from global register", silent = false },
  { "<leader>y", "\"+y", desc = "Copy marked text to global register", mode = "v", silent = false },
  { "<up>", ":resize -2<CR>", desc = "Decrease vertical size" },
  { "<down>", ":resize +2<CR>", desc = "Increase vertical size" },
  { "<left>", ":vertical resize +2<CR>", desc = "Left horizontal resize" },
  { "<right>", ":vertical resize -2<CR>", desc = "Right horizontal resize" },
  { "-", ":Explore<CR>", desc = "Toggle file explorer" },
  { "//", [[y/\V<C-R>=escape(@",'/\')<CR><CR>]], desc = "Search current marked text", mode = "v" },
  { "<C-h>", "<C-w>h", desc = "Switch to left region" },
  { "<C-j>", "<C-w>j", desc = "Switch to bottom region" },
  { "<C-k>", "<C-w>k", desc = "Switch to top region" },
  { "<C-l>", "<C-w>l", desc = "Switch to right region" },
  { "<C-h>", [[<C-\><C-n><C-w>h]], desc = "Switch to left region", mode = "t" },
  { "<C-j>", [[<C-\><C-n><C-w>j]], desc = "Switch to bottom region", mode = "t" },
  { "<C-k>", [[<C-\><C-n><C-w>k]], desc = "Switch to top region", mode = "t" },
  { "<C-l>", [[<C-\><C-n><C-w>l]], desc = "Switch to right region", mode = "t" },
})
